config/routes.rb
Rails.application.routes.draw do
  resources :flights, :bookings
  root 'flights#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: :from_airport
  has_many :arriving_flights, class_name: 'Flight', foreign_key: :to_airport
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, class_name: 'Airport'
  belongs_to :to_airport, class_name: 'Airport'

  has_many :bookings
  has_many :passengers, through: :bookings

  def formatted_duration
    "#{duration / 1.hour}h #{duration % 1.hour}m"
  end

  def formatted_departure
    departure.strftime('%d/%m/%Y %H:%M')
  end
end

app/models/flight_search.rb
class FlightSearch < ApplicationRecord
  alias_attribute :from_airport, :from
  alias_attribute :to_airport, :to
  alias_attribute :departure, :departs
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  def new
    redirect_back fallback_location: root_path, alert: 'Please select passengers count and search again' if booking_params[:passengers].empty?
    @booking = Booking.new({ flight_id: booking_params[:flight_id] })
    p @booking
    booking_params[:passengers].to_i.times do
      @booking.passengers.build
    end
    @flight = @booking.flight
  end

  def create
    @booking = Booking.new(create_booking_params)
    @flight = @booking.flight
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_back fallback_location: root_path, alert: @booking.errors.full_messages.to_sentence
    end
  end

  private

  def booking_params
    params.require(:booking).permit(%i[flight_id passengers])
  end

  def create_booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[id name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flight_search = FlightSearch.new(search_params)
    @flights = Flight.includes(:from_airport, :to_airport).where(flight_params).all
  end

  private

  def search_params
    params.fetch(:flight_search, {}).permit(%i[from_airport to_airport departure passengers]).delete_if { |_, v| v.empty? }
  end

  def flight_params
    params.fetch(:flight_search, {}).permit(%i[from_airport to_airport departure]).delete_if { |_, v| v.empty? }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Book a Flight</h1>
<% if flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<section>
  <table>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Departure</th>
      <th>Duration</th>
    </tr>
    <tr>
      <td><%= @flight.from_airport.code %></td>
      <td><%= @flight.to_airport.code %></td>
      <td><%= @flight.departure.strftime('%d/%m/%Y %H:%M') %></td>
      <td><%= "#{@flight.duration / 1.hour}h #{@flight.duration % 1.hour}m" %></td>
    </tr>
  </table>
</section>
<%= form_with model: @booking do |form| %>
  <h2>Passengers</h2>
  <ol>
    <%= form.fields_for :passengers do |passenger_form| %>
      <li>
        <%= passenger_form.label :name %>
        <%= passenger_form.text_field :name, required: true %>

        <%= passenger_form.label :email %>
        <%= passenger_form.email_field :email, required: true %>
      </li>
    <% end %>
  </ol>
  <section>
    <%= form.hidden_field :flight_id %>
    <%= form.submit :create %>
  </section>
<% end %>

app/views/bookings/show.html.erb
<h1>Your Ticket</h1>

<article class="ticket">
  <table>
    <tr>
      <th colspan="4">Ticket for Flight #<%= @booking.flight.id %></th>
    </tr>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Departs</th>
      <th>Duration</th>
    </tr>
    <tr>
      <td><%= @flight.from_airport.code %></td>
      <td><%= @flight.to_airport.code %></td>
      <td><%= @flight.formatted_departure %></td>
      <td><%= @flight.formatted_duration %></td>
    </tr>
  </table>

  <table>
    <tr>
      <th colspan="2">Passengers</th>
    </tr>
    <tr>
      <th>name</th>
      <th>email</th>
    </tr>
    <% @booking.passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
      </tr>
    <% end %>
  </table>
</article>

app/views/flights/index.html.erb
<h1>Search Flights</h1>
<% if flash[:alert] %>
  <p class="alert"><%= flash[:alert] %></p>
<% end %>
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<%= form_with model: @flight_search, url: root_path, method: :get do |form| %>
  <section>
    <%= form.label :from_airport, 'From' %>
    <%= form.collection_select :from_airport, [[nil,'Select an Airport'], *Airport.all.map{|n| [n.id,n.code]}], :first, :second %>
    <%= form.label :to_airport, "To" %>
    <%= form.collection_select :to_airport, [[nil,'Select an Airport'], *Airport.all.map{|n| [n.id,n.code]}], :first, :second %>
  </section>

  <section>
    <%= form.label :passengers %>
    <%= form.collection_radio_buttons :passengers, (1..4).map{|n| [n, n]}, :first, :second %>
  </section>

  <section>
    <%= form.label :departure %>
    <%= form.collection_select :departure, [[nil,'Any Date'], *Flight.select(:departure).distinct.order(:departure).map{|d| [d.departure,d.departure]}], :first, :second %>
  </section>

  <section>
    <%= form.submit 'Search' %>
  </section>
<% end %>

<% if @flights %>
  <h2>Flights:</h2>

  <table>
    <tr>
      <th>From</th>
      <th>To</th>
      <th>Departure</th>
      <th>Duration</th>
      <th></th>
    </tr>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.from_airport.code %></td>
        <td><%= flight.to_airport.code %></td>
        <td><%= flight.departure.strftime('%d/%m/%Y %H:%M') %></td>
        <td><%= "#{flight.duration / 1.hour}h #{flight.duration % 1.hour}m" %></td>
        <td><%= link_to 'Book a Flight', new_booking_path(booking: {flight_id: flight.id, passengers: @flight_search.passengers}) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>